services:
  - type: web
    name: gamer-preferences-dashboard
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:server
    autoDeploy: true
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: GOOGLE_SHEET_NAME
        sync: false
      - key: GOOGLE_WORKSHEET_NAME
        sync: false
      - key: GOOGLE_SERVICE_ACCOUNT_JSON
        sync: false
      - key: SYNC_FROM_GOOGLE_SHEETS
        value: "true"
      - key: SYNC_INTERVAL_SECONDS
        value: "2"
      - key: DASH_DEBUG
        value: "false"
